### PR TITLE
Add getlandr.io Netlify site redirects.

### PR DESCRIPTION
**Pull request by iamsolankiamit**
Change-type: patch
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>

### CODE REVIEW

**Comment by iamsolankiamit** [comment]
@cmfcruz i though the transformer would be removed :/

**Comment by cmfcruz** [comment]
@balena-ci I self-certify!

**Review by cmfcruz — APPROVED** [review]

**Comment by cmfcruz** [comment]
@balena-ci retest

**Comment by cmfcruz** [comment]
@balena-ci retest

**Pull request merged**
