### PR TITLE
Fix repository URL in reserved for you

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Hi 
My PC has problems with Landr, so i cant test this change. Hope it helps.

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
@LucianBuzzo what am i doing here wrong?

**Comment by LucianBuzzo** [comment]
Hey @AlexProgrammerDE it looks like landrbot has some issues when trying to build the landr site for landr (a bit of a "yo dawg" moment :joy:). I don't think its something your doing.
I'm still working on improving the local development flow, as it is a bit clunky - I'd be interested to know what problems you faced on your PC: would you mind opening an issue describing what the friction was?

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@AlexProgrammerDE I tracked down the issue - scrutinizer (the tool landr does to gather info about a repo) uses puppeteer to gather screenshots. Unfortunately, puppeteer wasn't launching due to missing libraries and incorrect config. I've opened PRs to fix the issue, the landr one is here https://github.com/product-os/landr/pull/302
I already hotfixed the landrbot installation, so it should be functioning correctly now.

**Comment by AlexProgrammerDE** [comment]
@LucianBuzzo seems like the hotfix isnt working.

**Comment by AlexProgrammerDE** [comment]
@LucianBuzzo shouldn't Landrbot do only one comment?

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Pull request merged**
